name: CI_action

on:
    push:
        branches: [main/cise_ass1a_worksheet3_backend]
    pull_request:
        branches: [main]    

   
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [12.x]
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Run the tests
      run: npm test

    - name: Build
      run: npm run build # Modify this command based on your build script in package.json

    

  